sequencer: truncate lockfile and ref to NAME_MAX
Some commits may have unusually long subject lines, which can cause git
error out.
Currently the sequencer and lockfile assumes these to be less than
NAME_MAX which is the maximum length of a filename (on Linux).

When reproduced one is met by the error message:
$ git rebase --continue
error: cannot lock ref 'refs/rewritten/SANITIZED-SUBJECT': Unable to
create '.git/refs/rewritten/SANITIZED-SUBJECT.lock': File name too long
- where SANITIZED-SUBJECT is very long

Affected repos can only be salvaged through filter-branch etc.

Signed-off-by: Mark Ruvald Pedersen <mped@demant.com>